In [ ]:
distance = [10,15,17,24]
time = [.30,.47,.55,1.20]

In [3]:
import numpy as np

In [ ]:
np.

In [9]:
np_distance = np.array(distance)
np_time = pratik.array(time)
speed = np_distance/np_time

In [1]:
np_distance

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\selector_events.py", line 125, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\selector_events.py", line 125, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed b

NameError: name 'np_distance' is not defined

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\selector_events.py", line 125, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\selector_events.py", line 125, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed b

In [10]:
speed

array([33.33333333, 31.91489362, 30.90909091, 20.        ])

In [11]:
np_city = np.array(['NYC','LA','Miami', 'Houston'])

In [12]:
np_city.ndim

1

In [3]:
np_city_with_state = np.array([['NYC','LA','Miami', 'Houston'],['NY','CA','FL','TX'],['hjf','hfkjdh','jl','jl']])

In [16]:
np_city.shape

(4,)

In [4]:
np_city_with_state.shape

(3, 4)

In [5]:
np_city_with_state.ndim

2

In [17]:
np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [18]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

In [19]:
np_city_with_state.dtype

dtype('<U7')

In [29]:
first_trial_cyclist = [10,15,17,26]

In [30]:
second_trial_cyclist = [12,11,21,24]

In [31]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [32]:
np_second_trial_cyclist = np.array(second_trial_cyclist)

In [37]:
np_first_trail_cyclist+np_second_trial_cyclist

array([24, 22, 42, 48])

In [9]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [12]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [14]:
first_trial = cyclist_trials[0]

In [15]:
first_trial

array([10, 15, 17, 26])

In [16]:
first_trial.shape

(4,)

In [45]:
element = cyclist_trials[1][1]
element

11

In [17]:
cyclist_trials

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [32]:
cyclist_trials[0:1 , 3:4]

array([[26]])

In [19]:
cyclist_trials[1:2 , 1:3]

array([[11, 21]])

In [18]:
cyclist_trials[0:2 , 2:3]

array([[17],
       [21]])

In [48]:
cyclist_trials[0:2,1:3]

array([[15, 17],
       [11, 21]])

In [49]:
cyclist_trials[1:2,2:4]

array([[21, 24]])

In [50]:
two_cyclist_trial_data = cyclist_trials[:,1:3]

In [51]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [52]:
for iterate_cyclist_trials_data in cyclist_trials:
    print(iterate_cyclist_trials_data)

[10 15 17 26]
[12 11 21 24]


In [53]:
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print(iterate_two_cyclist_trial_data)

[15 17]
[11 21]


In [35]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [55]:
passing_score = test_scores>60

In [56]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [8]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [58]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [59]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [60]:
b = a.copy()

In [61]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
b[0][1]

2

In [63]:
b[0][1] = 9
b

array([[1, 9, 3],
       [4, 5, 6]])

In [64]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
c = a.view()
c

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
c[1][1]

5

In [67]:
c[1][1] = 8

In [68]:
c

array([[1, 2, 3],
       [4, 8, 6]])

In [69]:
a

array([[1, 2, 3],
       [4, 8, 6]])

In [70]:
# View changes the original , as view takes storage from original data
#Copy doesn't

In [71]:
np_sqrt = np.sqrt([2,4,9,16])

In [72]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [36]:
np.sin(np.pi/2)

1.0

In [73]:
from numpy import pi
np.cos(0)

1.0

In [74]:
np.sin(pi/2)

1.0

In [75]:
np.cos(pi)

-1.0

In [76]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [77]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

# shape

In [78]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [79]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [80]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [81]:
new_cyclist_trials.resize(2,6)

In [82]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [84]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]), array([[26, 13, 19],
        [24, 14, 23]])]

In [85]:
new_cyclist_1 = np.array([10,15,17,26,13,19])

In [86]:
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [88]:
np.hstack([new_cyclist_1,new_cyclist_2])

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [ ]:
array_a = np.array([2,3,5,8])
array_b = np.array([])

In [3]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [4]:
passing_score = test_scores>60

In [5]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [7]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [9]:
NYC_Borough =  np.array(['Manhattan', 'Bronx','Brooklyn', 'Staten Island', 'Queens'])

In [10]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [11]:
Borough_in_NYC = NYC_Borough

In [12]:
Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [13]:
Borough_in_NYC is NYC_Borough

True

# Broadcasting

In [14]:
#creating two arrays of the same shape
array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [15]:
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [16]:
scaler_c = .3

In [17]:
array_a * scaler_c

array([0.6, 0.9, 1.5, 2.4])

# transpose

In [18]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [20]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [22]:
test_scores.T

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

# Linear algebra - Inverse and Trace

In [23]:
inverse_array = np.array([[10,20],[15,25]])

In [24]:
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [27]:
trace_array = np.array([[10,20],[22,31]])
trace_array

array([[10, 20],
       [22, 31]])

In [28]:
np.trace(trace_array) #sum of diagonal array

41

# Pandas

In [29]:
import numpy as np
import pandas as pd

In [30]:
first_series = pd.Series(list('abcdef'))

In [31]:
print(first_series)

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object


In [39]:
np_country = np.array(['Luxembourg','Norway','Japan', 'Switzerland', 'United States','Qatar','Iceland','Sweden','Singapore', 'Denmark'])
np_country

array(['Luxembourg', 'Norway', 'Japan', 'Switzerland', 'United States',
       'Qatar', 'Iceland', 'Sweden', 'Singapore', 'Denmark'], dtype='<U13')

In [36]:
s_country = pd.Series(np_country)
s_country

0       Luxembourg
1           Norway
2            Japan
3      Switzerland
4    United States
5            Qatar
6          Iceland
7           Sweden
8        Singapore
9          Denmark
dtype: object

In [42]:
#Evaluate countries and their correspondinggdp per capita and print them as series
dict_country_gdp = pd.Series([52056.01781,40258.80862,40034.85063,39578.07441,39170.41371,37958.23146,37691.02733,36125.66676,34706.19047,33630.24604,33529.83052,30860.12808], index = ['Luxembourg','Macao, China', 'Norway', 'Japan','Switzerlan','Hong Kong, China','United States', 'Qatar','Iceland','Sweden','Singapore','Denmark'])
dict_country_gdp

Luxembourg          52056.01781
Macao, China        40258.80862
Norway              40034.85063
Japan               39578.07441
Switzerlan          39170.41371
Hong Kong, China    37958.23146
United States       37691.02733
Qatar               36125.66676
Iceland             34706.19047
Sweden              33630.24604
Singapore           33529.83052
Denmark             30860.12808
dtype: float64

In [44]:
dict_country_gdp.iloc[3] #accessing for Japan

39578.07441

In [45]:
dict_country_gdp.loc['Japan'] 

39578.07441

# create series from scalar

In [46]:
#print series with scalar input
scalar_series = pd.Series(5, index = ['a','b','c','d','e'])

In [47]:
scalar_series

a    5
b    5
c    5
d    5
e    5
dtype: int64

# Vectorize operation in series

In [48]:
first_vector_series = pd.Series([1,2,3,4], index = ['a','b', 'c','d'])
second_vector_series = pd.Series([10,20,30,40], index = ['a', 'b','c','d'])

In [49]:
first_vector_series+second_vector_series

a    11
b    22
c    33
d    44
dtype: int64

In [50]:
second_vector_series = pd.Series([10,20,30,40], index = ['a','d','b','c'])

In [52]:
first_vector_series+second_vector_series

a    11
b    32
c    43
d    24
dtype: int64

In [12]:
first_series = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])

In [13]:
second_series = pd.Series([10,20,30,40,50], index = ['c','e','f','g','h'])

In [55]:
sum_of_series = first_series+second_series
sum_of_series

a     NaN
b     NaN
c    13.0
d     NaN
e    25.0
f     NaN
g     NaN
h     NaN
dtype: float64

In [56]:
# drop NaN(Not a Number) Values 
dropna_s = sum_of_series.dropna()

In [57]:
dropna_s

c    13.0
e    25.0
dtype: float64

In [60]:
dropna_s.fillna(0)

c    13.0
e    25.0
dtype: float64

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\selector_events.py", line 125, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ppluc\Anaconda3\lib\asyncio\selector_events.py", line 125, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed b

In [59]:
#filling that NaN values with 0
fillna_s = sum_of_series.fillna(0)
fillna_s

a     0.0
b     0.0
c    13.0
d     0.0
e    25.0
f     0.0
g     0.0
h     0.0
dtype: float64

In [1]:
import pandas as pd

In [2]:
olympic_data_list = {'HostCity':['London','Beijing','Athens','Sydney','Atlanta'],'Year':[2012,2008,2004,2000,1996],'No. of Participating Countries':[205,204,201,200,197]}

In [5]:
df_olympic_data = pd.DataFrame(olympic_data_list)
df_olympic_data

HostCity  Year  No. of Participating Countries
0   London  2012                             205
1  Beijing  2008                             204
2   Athens  2004                             201
3   Sydney  2000                             200
4  Atlanta  1996                             197

In [8]:
df_olympic_data.Year

0    2012
1    2008
2    2004
3    2000
4    1996
Name: Year, dtype: int64

In [9]:
df_olympic_data['Year']

0    2012
1    2008
2    2004
3    2000
4    1996
Name: Year, dtype: int64

In [10]:
df_olympic_data[['Year','HostCity']]

Year HostCity
0  2012   London
1  2008  Beijing
2  2004   Athens
3  2000   Sydney
4  1996  Atlanta

In [14]:
fill_NaN_with_zero_before_sum = first_series.add(second_series, fill_values=0)

TypeError: flex_wrapper() got an unexpected keyword argument 'fill_values'

In [15]:
df_movie_rating = pd.DataFrame({'movie 1': [5,4,3,3,2,1],'movie 2': [4,5,2,3,4,2]},index = ['Tom','Jeff','Peter','Ram','Ted','Paul'])

In [16]:
df_movie_rating

movie 1  movie 2
Tom          5        4
Jeff         4        5
Peter        3        2
Ram          3        3
Ted          2        4
Paul         1        2

In [20]:
def movie_ratings(grade):
    if grade == 5:
        return 'A'
    if grade == 4:
        return 'B'
    if grade == 3:
        return 'C'
    if grade == 2:
        return 'D'
    if grade == 1:
        return 'E'
    else:
        return 'F'
    
print( movie_ratings(5))

A


In [21]:
df_movie_rating.applymap(movie_ratings)

movie 1 movie 2
Tom         A       B
Jeff        B       A
Peter       C       D
Ram         C       C
Ted         D       B
Paul        E       D

In [22]:
df_movie_rating.replace([5],'a')

movie 1 movie 2
Tom         a       4
Jeff        4       a
Peter       3       2
Ram         3       3
Ted         2       4
Paul        1       2

In [23]:
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ] 
roll_no = [ 4, 1, 3, 2 ] 
marks = [ 40, 50, 60, 70 ]
new = zip(name, roll_no, marks)
#o/p-{('Shambhavi', 3, 60), ('Astha', 2, 70),('Manjeet', 4, 40), ('Nikhil', 1, 50)}

In [26]:
print(new)

In [1]:
import numpy as np 
import pandas as pd

In [2]:
salary = pd.read_csv('salaries.csv')

In [3]:
salary

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [35]:
import os

In [37]:
os.getcwd()

'C:\\Users\\ppluc'

In [40]:
os.chdir("C:\\Users\\ppluc\\")

In [41]:
os.getcwd()

'C:\\Users\\ppluc'

In [4]:
salary.describe()

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [6]:
salary['salary'].dtypes

dtype('int64')

In [7]:
salary.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [8]:
salary.axes

[RangeIndex(start=0, stop=78, step=1),
 Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')]

In [9]:
salary.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [10]:
salary.ndim

2

In [11]:
salary.count()

rank          78
discipline    78
phd           78
service       78
sex           78
salary        78
dtype: int64

In [33]:
print(count(salary.columns))

NameError: name 'count' is not defined

In [16]:
salary.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [17]:
salary.describe()

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [18]:
salary.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [19]:
salary.tail()

rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [23]:
salary.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [24]:
salary.mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [25]:
salary.median()

phd            18.5
service        14.5
salary     104671.0
dtype: float64

In [26]:
salary.std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [28]:
salary.sample()

rank discipline  phd  service   sex  salary
27  Prof          A   45       43  Male  155865

In [29]:
salary.dropna()

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [30]:
salary.salary.mean()

108023.78205128205

In [36]:
salary.head(50).mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [37]:
salary['salary'].describe()

count        78.000000
mean     108023.782051
std       28293.661022
min       57800.000000
25%       88612.500000
50%      104671.000000
75%      126774.750000
max      186960.000000
Name: salary, dtype: float64

In [38]:
salary['salary'].count()

78

In [39]:
salary['salary'].mean()

108023.78205128205

In [40]:
df_rank = salary.groupby(['rank'])

In [41]:
df_rank

In [42]:
df_rank.mean()

phd    service         salary
rank                                          
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [44]:
salary.groupby('rank')['salary'].mean()

rank
AssocProf     91786.230769
AsstProf      81362.789474
Prof         123624.804348
Name: salary, dtype: float64

In [46]:
df_rank['salary'].mean()

rank
AssocProf     91786.230769
AsstProf      81362.789474
Prof         123624.804348
Name: salary, dtype: float64

In [52]:
df_sub = salary[salary['salary'] > 120000]
df_sub

rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [51]:
df_sub.count()

rank          25
discipline    25
phd           25
service       25
sex           25
salary        25
dtype: int64

In [54]:
df_f = salary[salary['sex'] == 'Female']
df_f

rank discipline  phd  service     sex  salary
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [57]:
df_both = salary[(salary['sex']=='Female') &(salary['salary']>120000)]
df_both

rank discipline  phd  service     sex  salary
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [69]:
salary.iloc[5:15]

rank discipline  phd  service   sex  salary
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750

In [70]:
salary.loc[5:15]

rank discipline  phd  service   sex  salary
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750
15       Prof          B   17        3  Male  150480

In [5]:
salary.loc[[14,26,31],['phd','sex']]

phd   sex
14   25  Male
26   38  Male
31   22  Male

In [6]:
salary.iloc[3:9,[1,3,5]]

discipline  service  salary
3          A       31  131205
4          B       18  104800
5          A       20  122400
6          A       17   81285
7          A       18  126300
8          A       19   94350

In [9]:
salary(salary[['rank']=='AsstProf'])

KeyError: False

In [10]:
df_sorted = salary.sort_values(by = 'service')

In [11]:
df_sorted

rank discipline  phd  service     sex  salary
55  AsstProf          A    2        0  Female   72500
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000
..       ...        ...  ...      ...     ...     ...
40      Prof          A   39       36  Female  137000
27      Prof          A   45       43    Male  155865
36      Prof          B   45       45    Male  146856
0       Prof          B   56       49    Male  186960
9       Prof          A   51       51    Male   57800

[78 rows x 6 columns]

In [15]:
df_sorted = salary.sort_values(by = 'service',ascending=False)
df_sorted

rank discipline  phd  service     sex  salary
9       Prof          A   51       51    Male   57800
0       Prof          B   56       49    Male  186960
36      Prof          B   45       45    Male  146856
27      Prof          A   45       43    Male  155865
40      Prof          A   39       36  Female  137000
..       ...        ...  ...      ...     ...     ...
43  AsstProf          B    5        0  Female   77000
52      Prof          A   12        0  Female  105000
12  AsstProf          B    1        0    Male   88000
23  AsstProf          A    2        0    Male   85000
55  AsstProf          A    2        0  Female   72500

[78 rows x 6 columns]

In [16]:
df_sorted = salary.sort_values(by = ['sex','salary'],ascending=[True,False])
df_sorted

rank discipline  phd  service     sex  salary
72       Prof          B   24       15  Female  161101
44       Prof          B   23       19  Female  151768
58       Prof          B   36       26  Female  144651
45       Prof          B   25       25  Female  140096
40       Prof          A   39       36  Female  137000
..        ...        ...  ...      ...     ...     ...
23   AsstProf          A    2        0    Male   85000
6   AssocProf          A   20       17    Male   81285
16   AsstProf          B    8        3    Male   75044
22   AsstProf          A    4        2    Male   73000
9        Prof          A   51       51    Male   57800

[78 rows x 6 columns]

In [20]:
import os 
flight = pd.read_csv('C:\\Users\\ppluc\\Downloads\\flights .csv')

In [21]:
flight


year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
0       2013      1    1     517.0        2.0     830.0       11.0      UA   
1       2013      1    1     533.0        4.0     850.0       20.0      UA   
2       2013      1    1     542.0        2.0     923.0       33.0      AA   
3       2013      1    1     554.0       -6.0     812.0      -25.0      DL   
4       2013      1    1     554.0       -4.0     740.0       12.0      UA   
...      ...    ...  ...       ...        ...       ...        ...     ...   
160749  2013      9   30    2105.0       -1.0    2329.0      -25.0      UA   
160750  2013      9   30    2121.0       21.0    2349.0      -25.0      DL   
160751  2013      9   30    2140.0        0.0      10.0      -30.0      AA   
160752  2013      9   30    2149.0       -7.0    2245.0      -23.0      UA   
160753  2013      9   30    2233.0       80.0     112.0       42.0      UA   

       tailnum  flight origin dest  air_time  distance  hour  minute  
0       N14228    1545    EWR  IAH     227.0      1400   5.0    17.0  
1       N24211    1714    LGA  IAH     227.0      1416   5.0    33.0  
2       N619AA    1141    JFK  MIA     160.0      1089   5.0    42.0  
3       N668DN     461    LGA  ATL     116.0       762   5.0    54.0  
4       N39463    1696    EWR  ORD     150.0       719   5.0    54.0  
...        ...     ...    ...  ...       ...       ...   ...     ...  
160749  N477UA     475    EWR  IAH     175.0      1400  21.0     5.0  
160750  N193DN    2363    JFK  LAX     296.0      2475  21.0    21.0  
160751  N335AA     185    JFK  LAX     298.0      2475  21.0    40.0  
160752  N813UA     523    EWR  BOS      37.0       200  21.0    49.0  
160753  N578UA     471    EWR  SFO     318.0      2565  22.0    33.0  

[160754 rows x 16 columns]

In [22]:
flight[flight.isnull().any(axis=1)].head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
330  2013      1    1    1807.0       29.0    2251.0        NaN      UA   
403  2013      1    1       NaN        NaN       NaN        NaN      AA   
404  2013      1    1       NaN        NaN       NaN        NaN      AA   
855  2013      1    2    2145.0       16.0       NaN        NaN      UA   
858  2013      1    2       NaN        NaN       NaN        NaN      AA   

    tailnum  flight origin dest  air_time  distance  hour  minute  
330  N31412    1228    EWR  SAN       NaN      2425  18.0     7.0  
403  N3EHAA     791    LGA  DFW       NaN      1389   NaN     NaN  
404  N3EVAA    1925    LGA  MIA       NaN      1096   NaN     NaN  
855  N12221    1299    EWR  RSW       NaN      1068  21.0    45.0  
858     NaN     133    JFK  LAX       NaN      2475   NaN     NaN

In [23]:
flight.notnull()

year  month   day  dep_time  dep_delay  arr_time  arr_delay  carrier  \
0       True   True  True      True       True      True       True     True   
1       True   True  True      True       True      True       True     True   
2       True   True  True      True       True      True       True     True   
3       True   True  True      True       True      True       True     True   
4       True   True  True      True       True      True       True     True   
...      ...    ...   ...       ...        ...       ...        ...      ...   
160749  True   True  True      True       True      True       True     True   
160750  True   True  True      True       True      True       True     True   
160751  True   True  True      True       True      True       True     True   
160752  True   True  True      True       True      True       True     True   
160753  True   True  True      True       True      True       True     True   

        tailnum  flight  origin  dest  air_time  distance  hour  minute  
0          True    True    True  True      True      True  True    True  
1          True    True    True  True      True      True  True    True  
2          True    True    True  True      True      True  True    True  
3          True    True    True  True      True      True  True    True  
4          True    True    True  True      True      True  True    True  
...         ...     ...     ...   ...       ...       ...   ...     ...  
160749     True    True    True  True      True      True  True    True  
160750     True    True    True  True      True      True  True    True  
160751     True    True    True  True      True      True  True    True  
160752     True    True    True  True      True      True  True    True  
160753     True    True    True  True      True      True  True    True  

[160754 rows x 16 columns]

In [24]:
flight1 = flight.copy()

In [25]:
flight1

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
0       2013      1    1     517.0        2.0     830.0       11.0      UA   
1       2013      1    1     533.0        4.0     850.0       20.0      UA   
2       2013      1    1     542.0        2.0     923.0       33.0      AA   
3       2013      1    1     554.0       -6.0     812.0      -25.0      DL   
4       2013      1    1     554.0       -4.0     740.0       12.0      UA   
...      ...    ...  ...       ...        ...       ...        ...     ...   
160749  2013      9   30    2105.0       -1.0    2329.0      -25.0      UA   
160750  2013      9   30    2121.0       21.0    2349.0      -25.0      DL   
160751  2013      9   30    2140.0        0.0      10.0      -30.0      AA   
160752  2013      9   30    2149.0       -7.0    2245.0      -23.0      UA   
160753  2013      9   30    2233.0       80.0     112.0       42.0      UA   

       tailnum  flight origin dest  air_time  distance  hour  minute  
0       N14228    1545    EWR  IAH     227.0      1400   5.0    17.0  
1       N24211    1714    LGA  IAH     227.0      1416   5.0    33.0  
2       N619AA    1141    JFK  MIA     160.0      1089   5.0    42.0  
3       N668DN     461    LGA  ATL     116.0       762   5.0    54.0  
4       N39463    1696    EWR  ORD     150.0       719   5.0    54.0  
...        ...     ...    ...  ...       ...       ...   ...     ...  
160749  N477UA     475    EWR  IAH     175.0      1400  21.0     5.0  
160750  N193DN    2363    JFK  LAX     296.0      2475  21.0    21.0  
160751  N335AA     185    JFK  LAX     298.0      2475  21.0    40.0  
160752  N813UA     523    EWR  BOS      37.0       200  21.0    49.0  
160753  N578UA     471    EWR  SFO     318.0      2565  22.0    33.0  

[160754 rows x 16 columns]

In [26]:
flight1.fillna(0)

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
0       2013      1    1     517.0        2.0     830.0       11.0      UA   
1       2013      1    1     533.0        4.0     850.0       20.0      UA   
2       2013      1    1     542.0        2.0     923.0       33.0      AA   
3       2013      1    1     554.0       -6.0     812.0      -25.0      DL   
4       2013      1    1     554.0       -4.0     740.0       12.0      UA   
...      ...    ...  ...       ...        ...       ...        ...     ...   
160749  2013      9   30    2105.0       -1.0    2329.0      -25.0      UA   
160750  2013      9   30    2121.0       21.0    2349.0      -25.0      DL   
160751  2013      9   30    2140.0        0.0      10.0      -30.0      AA   
160752  2013      9   30    2149.0       -7.0    2245.0      -23.0      UA   
160753  2013      9   30    2233.0       80.0     112.0       42.0      UA   

       tailnum  flight origin dest  air_time  distance  hour  minute  
0       N14228    1545    EWR  IAH     227.0      1400   5.0    17.0  
1       N24211    1714    LGA  IAH     227.0      1416   5.0    33.0  
2       N619AA    1141    JFK  MIA     160.0      1089   5.0    42.0  
3       N668DN     461    LGA  ATL     116.0       762   5.0    54.0  
4       N39463    1696    EWR  ORD     150.0       719   5.0    54.0  
...        ...     ...    ...  ...       ...       ...   ...     ...  
160749  N477UA     475    EWR  IAH     175.0      1400  21.0     5.0  
160750  N193DN    2363    JFK  LAX     296.0      2475  21.0    21.0  
160751  N335AA     185    JFK  LAX     298.0      2475  21.0    40.0  
160752  N813UA     523    EWR  BOS      37.0       200  21.0    49.0  
160753  N578UA     471    EWR  SFO     318.0      2565  22.0    33.0  

[160754 rows x 16 columns]

In [27]:
flight[['dep_delay','arr_delay']].agg(['min','max','mean'])

dep_delay    arr_delay
min    -33.000000   -75.000000
max   1014.000000  1007.000000
mean     9.463773     2.094537